"""user_id added in customer

Revision ID: 10cceb784195
Revises: 9f943a2967dc
Create Date: 2024-03-03 17:01:10.190280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cceb784195'
down_revision: Union[str, None] = '9f943a2967dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costumer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'costumer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'costumer', type_='foreignkey')
    op.drop_column('costumer', 'user_id')
    # ### end Alembic commands ###
